### ISSUE TITLE
Remove init_javascript_enhancement usage

### ISSUE THREAD

**Issue by ankitagarwal** [moodlehq/moodle-local_hub#42]
Refer to MDL-57471

Currently on course home page, local hub is throwing following notice - 
line 249 of /local/hub/forms.php: call to moodleform->init_javascript_enhancement()
line 204 of /lib/formslib.php: call to course_search_form->definition()
line 1765 of /local/hub/lib.php: call to moodleform->__construct()
line 99 of /index.php: call to local_hub->display_homepage()

**Comment by danpoltawski** [comment]
I made a patch, as far as I can see it was only behaving as a select anyway!
